[versions]

# @see jackson
# @see ktor
# @see kotlinx-coroutines
# Changelog: https://github.com/JetBrains/kotlin/blob/master/ChangeLog.md
kotlin = "1.6.20"
kotlinx-html = "0.7.3"
# @see kotlin
kotlinx-coroutines = "1.5.2"

dagger = "2.42"

jackson = "2.13.2"

slf4j = "1.7.31"

test-junit-vintage = "4.13.2"
# @see test-junit-platform
test-junit-jupiter = "5.7.2"
# @see test-junit-jupiter
test-junit-platform = "1.7.2"

test-jfixture = "2.7.2"

[libraries]

kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-apt = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }

jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-dataformat-xml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-xml", version.ref = "jackson" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jackson-datatype-java8 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }

slf4j-core = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-log4j12 = { module = "org.slf4j:slf4j-log4j12", version.ref = "slf4j" }
slf4j-jul = { module = "org.slf4j:jul-to-slf4j", version.ref = "slf4j" }

test-junit-platform = { module = "org.junit.platform:junit-platform-launcher", version.ref = "test-junit-platform" }
test-junit-jupiter = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "test-junit-jupiter" }
test-junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "test-junit-jupiter" }
test-junit-vintage = { module = "junit:junit", version.ref = "test-junit-vintage" }

test-jfixture = { module = "com.flextrade.jfixture:jfixture", version.ref = "test-jfixture" }

[bundles]

[plugins]
