name: Delete from Google App Engine
on:
  pull_request:
    types: closed
  delete:
  # branches
  workflow_dispatch:
  # no inputs
jobs:
  release:
    name: Delete from Google App Engine
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # Only trigger when deleting branches, or any other event type.
    if: github.event_name != 'delete' || github.event.ref_type == 'branch'
    permissions:
      contents: read  # This is required for actions/checkout.
      # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#updating-your-actions-for-oidc
      id-token: write # This is required for requesting the JWT via google-github-actions/auth.
    steps:
      - name: Determine Google App Engine version name.
        id: name
        uses: actions/github-script@v6
        with:
          script: |
            const branch = {
              // on:pull_request:closed[pull_request.merged]'s ref is the base branch's simple name.
              // on:pull_request:closed[!pull_request.merged]'s ref is the merge branch.
              // So reconstruct the merge branch name in both cases.
              pull_request: `refs/pull/${context.payload.number}/merge`,
              // on:delete's context.ref is always `refs/heads/master`
              // So use github.event.ref which is just the name, so polyfill with prefix to be consistent for next steps.
              // See https://stackoverflow.com/a/62293570/253468
              delete: `refs/heads/${context.payload.ref}`,
              // on:workflow_dispatch's ref is the full ref selected in the UI, so use it as-is.
              workflow_dispatch: context.ref,
            }[context.eventName]
            return branch
              // refs/heads/master from workflow_dispatch and delete events.
              .replace('refs/heads/', 'br-')
              // refs/pull/123/merge from pull_request.closed event.
              .replace('refs/pull/', 'pr-')
              // ERROR: (gcloud.app.deploy) argument --version/-v: Bad value [...]:
              // May only contain lowercase letters, digits, and hyphens.
              // Must begin and end with a letter or digit. Must not exceed 63 characters.
              .replace(/[^a-z0-9-]/g, '-')

      - name: Checkout ${{ github.ref }} branch in ${{ github.repository }} repository.
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud.
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GAE_WIP }}
          service_account: ${{ secrets.GAE_SA }}

      - name: Print tooling versions.
        run: |
          gcloud --version

      - name: Delete version ${{ steps.name.outputs.result }} from Google App Engine.
        run: |
          gcloud app versions delete --quiet --project="twisterrob-cinema" ${{ steps.name.outputs.result }}
