name: "Generate random data"

on:
  workflow_dispatch:
  schedule:
    # At 03:00 on Thursdays.
    - cron: '0 3 * * 4'

jobs:

  generate:
    name: "Generate and import random data."
    timeout-minutes: 10

    permissions:
      # actions/checkout
      contents: read

    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash

    steps:

      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v4

      - name: "Set up Java."
        uses: actions/setup-java@v4
        with:
          java-version-file: Heroku/.java-version
          distribution: temurin

      - name: "Clean up workspace."
        run: |
          rm --verbose --force backend/sync/test/weekly_film_times.xml
          #rm --verbose --force backend/sync/test/weekly_film_times_ie.xml

      - name: "Generate random data."
        env:
          NEO4J_URL: ${{ secrets.NEO4J_URL }}
        working-directory: Heroku
        run: >
          ./gradlew
          :backend:sync:generate
          --args="test/weekly_film_times.xml"

      - name: "Upload 'weekly_film_times.xml'."
        uses: actions/upload-artifact@v4
        with:
          name: 'weekly_film_times.xml'
          if-no-files-found: error
          path: Heroku/backend/sync/test/weekly_film_times.xml

      - name: "Import generated data."
        env:
          NEO4J_URL: ${{ secrets.NEO4J_URL }}
        working-directory: Heroku
        run: >
          ./gradlew
          :backend:sync:run
          --args="--folder=test performances films"
