name: "🔨 Build & Check"
on:
  workflow_call:
    inputs:

      skip:
        description: |
          Pass the value from outside, so that nested jobs show up checks.
          This is needed to satisfy (Required) checks in branch protection rules.
        type: boolean
        default: false

jobs:

  gradle:
    uses: ./.github/workflows/Heroku-check-gradle.yml
    with:
      skip: ${{ inputs.skip }}

  npm:
    uses: ./.github/workflows/Heroku-check-npm.yml
    with:
      skip: ${{ inputs.skip }}
    secrets: inherit
