name: "🔨 Build & Check"
on:
  workflow_call:

jobs:

  validate:
    name: "🦺 Validation"
    uses: TWiStErRob/github-workflows/.github/workflows/validate.yml@5f662c65d1300162033c61e269cb2e63a26a990e # v3
    permissions:
      contents: read
      security-events: write
      actions: read

  gradle:
    name: "gradle"
    needs:
      - validate
    uses: ./.github/workflows/Heroku-check-gradle.yml
    permissions:
      contents: read
      checks: write
      security-events: write

  npm:
    name: "npm"
    needs:
      - validate
    uses: ./.github/workflows/Heroku-check-npm.yml
    permissions:
      contents: read
      checks: write
    secrets: inherit
