name: "Heroku"

on:
  push:
    branches-ignore:
      - 'release'

concurrency:
  # See https://github.com/TWiStErRob/github-workflows/blob/main/snippets/cancel-pr-ci-on-push.yml
  group: ${{ github.ref == 'refs/heads/main' && format('ci-heroku-main-{0}', github.sha) || format('ci-heroku-{0}', github.ref) }}
  cancel-in-progress: true

#env:
#  # Choose Java 17 explicitly via setup-java.
#  # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#java
#  # Don't set it here or even on the jobs, because this doesn't run on a runner, variables not available.
#  JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}

jobs:

  changes:
    name: "🝑 Determine changes"
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.Heroku }}
    steps:
      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v4

      - name: "Filter related paths to this workflow."
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            Heroku:
              - 'Heroku/**'
              - '.github/workflows/Heroku*.yml'

  check:
    name: "🔨 Build & Check"
    needs: changes
    if: needs.changes.outputs.changed == 'true'
    uses: ./.github/workflows/Heroku-check.yml

  pull_request:
    name: "Find PR"
    needs: changes
    if: needs.changes.outputs.changed == 'true'
    uses: ./.github/workflows/Heroku-pr.yml

  deps:
    name: "Calculate Dependency Diff"
    needs: pull_request
    if: needs.pull_request.outputs.found == 'true'
    uses: ./.github/workflows/Heroku-deps.yml
