name: "Find PR"

on:
  workflow_call:
    outputs:
      found:
        description: TODO
        value: ${{ jobs.find-pr.outputs.found }}
      base-ref:
        description: TODO
        value: ${{ jobs.find-pr.outputs.base-ref }}
      base-sha:
        description: TODO
        value: ${{ jobs.find-pr.outputs.base-sha }}
      head-ref:
        description: TODO
        value: ${{ jobs.find-pr.outputs.head-ref }}
      head-sha:
        description: TODO
        value: ${{ jobs.find-pr.outputs.head-sha }}

jobs:

  find-pr:
    name: "pull_request"
    runs-on: ubuntu-22.04
    timeout-minutes: 1

    permissions:
      # 8BitJonny/gh-get-current-pr
      pull-requests: read

    outputs:
      found: ${{ steps.current-pr.outputs.number != null }}
      # Simulate github.event.pull_request.base.ref on push trigger.
      base-ref: ${{ steps.current-pr.outputs.number != null && fromJSON(steps.current-pr.outputs.pr).base.ref }}
      base-sha: ${{ steps.current-pr.outputs.number != null && fromJSON(steps.current-pr.outputs.pr).base.sha }}
      # Simulate github.event.pull_request.head.ref on push trigger.
      head-ref: ${{ steps.current-pr.outputs.number != null && fromJSON(steps.current-pr.outputs.pr).head.ref }}
      head-sha: ${{ steps.current-pr.outputs.number != null && fromJSON(steps.current-pr.outputs.pr).head.sha }}

    steps:

      - name: "Determine which PR this commit belongs to, so we can clone its base branch for comparison."
        id: current-pr
        uses: 8BitJonny/gh-get-current-pr@3.0.0
        with:
          sha: ${{ github.event.pull_request.head.sha }}

      - name: "Pull Request #${{ steps.current-pr.outputs.number }}"
        shell: bash
        run: 'true'
