name: "Heroku"

on:
  push:
    branches:
      - 'main'
  pull_request:

concurrency:
  # See https://github.com/TWiStErRob/github-workflows/blob/main/snippets/cancel-pr-ci-on-push.yml
  group: ${{ github.ref == 'refs/heads/main' && format('ci-heroku-main-{0}', github.sha) || format('ci-heroku-{0}', github.ref) }}
  cancel-in-progress: true

#env:
#  # Choose Java 17 explicitly via setup-java.
#  # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#java
#  # Don't set it here or even on the jobs, because this doesn't run on a runner, variables not available.
#  JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}

jobs:

  check:
    name: "🔨 Build & Check"
    uses: ./.github/workflows/Heroku-check.yml
    secrets: inherit
    permissions:
      contents: read
      actions: read
      security-events: write
      checks: write

  pull-request:
    name: "Find PR"
    # Don't execute on main, it'll never be PR'd.
    if: ${{ github.ref != 'refs/heads/main' }}
    uses: ./.github/workflows/Heroku-pr.yml
    permissions:
      pull-requests: read

  deps:
    name: "Dependencies"
    needs: pull-request
    if: ${{ needs.pull-request.outputs.found == 'true' }}
    uses: ./.github/workflows/Heroku-deps.yml
    with:
      base-ref: ${{ needs.pull-request.outputs.base-ref }}
      base-sha: ${{ needs.pull-request.outputs.base-sha }}
      head-ref: ${{ needs.pull-request.outputs.head-ref }}
      head-sha: ${{ needs.pull-request.outputs.head-sha }}
    permissions:
      contents: read
      checks: write
      statuses: write
