name: "🔨 Build & Check"
on:
  workflow_call:
    inputs:
      if:
        type: boolean
        description: |
          Pass the value from outside, so that nested jobs show up checks.
          This is needed to satisfy (Required) checks in branch protection rules.
        default: true

jobs:

  gradle:
    uses: ./.github/workflows/Heroku-check-gradle.yml
    with:
      if: ${{ inputs.if }}

  npm:
    uses: ./.github/workflows/Heroku-check-npm.yml
    with:
      if: ${{ inputs.if }}
    secrets: inherit
