name: "Find PR"

on:
  workflow_call:
    outputs:
      found: ${{ jobs.pull_request.outputs.found }}
      base_ref: ${{ jobs.pull_request.outputs.base_ref }}
      base_sha: ${{ jobs.pull_request.outputs.base_sha }}
      head_ref: ${{ jobs.pull_request.outputs.head_ref }}
      head_sha: ${{ jobs.pull_request.outputs.head_sha }}

jobs:

  pull_request:
    runs-on: ubuntu-22.04
    timeout-minutes: 1

    outputs:
      found: ${{ steps.current_pr.outputs.number != null }}
      # Simulate github.event.pull_request.base.ref on push trigger.
      base_ref: ${{ steps.current_pr.outputs.number != null && fromJSON(steps.current_pr.outputs.pr).base.ref }}
      base_sha: ${{ steps.current_pr.outputs.number != null && fromJSON(steps.current_pr.outputs.pr).base.sha }}
      # Simulate github.event.pull_request.head.ref on push trigger.
      head_ref: ${{ steps.current_pr.outputs.number != null && fromJSON(steps.current_pr.outputs.pr).head.ref }}
      head_sha: ${{ steps.current_pr.outputs.number != null && fromJSON(steps.current_pr.outputs.pr).head.sha }}

    steps:

      - name: "Determine which PR this commit belongs to, so we can clone its base branch for comparison."
        id: current_pr
        uses: 8BitJonny/gh-get-current-pr@v2.2.0
        with:
          sha: ${{ github.event.pull_request.head.sha }}

      - name: "Pull Request #${{ steps.current_pr.outputs.number }}"
        run: true
