name: "Heroku"

on:
  push:

concurrency:
  # See https://github.com/TWiStErRob/github-workflows/blob/main/snippets/cancel-pr-ci-on-push.yml
  group: ${{ github.ref == 'refs/heads/main' && format('ci-heroku-main-{0}', github.sha) || format('ci-heroku-{0}', github.ref) }}
  cancel-in-progress: true

#env:
#  # Choose Java 17 explicitly via setup-java.
#  # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#java
#  # Don't set it here or even on the jobs, because this doesn't run on a runner, variables not available.
#  JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}

jobs:

  check:
    name: "🔨 Build & Check"
    uses: ./.github/workflows/Heroku-check.yml
    secrets: inherit

  pull_request:
    name: "Find PR"
    # Don't execute on main, it'll never be PR'd.
    if: github.ref != 'refs/heads/main'
    uses: ./.github/workflows/Heroku-pr.yml

  deps:
    name: "Calculate Dependency Diff"
    needs: pull_request
    uses: ./.github/workflows/Heroku-deps.yml
    with:
      base_ref: ${{ needs.pull_request.outputs.base_ref }}
      base_sha: ${{ needs.pull_request.outputs.base_sha }}
      head_ref: ${{ needs.pull_request.outputs.head_ref }}
      head_sha: ${{ needs.pull_request.outputs.head_sha }}

  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
