name: "🔨 Build & Execute (Map)"
on:
  workflow_call:

jobs:
  run:
    name: "run"
    # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
    timeout-minutes: 5

    permissions:
      # actions/checkout
      contents: read

    runs-on: ubuntu-22.04
    steps:

      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v4

      - name: "Set up Java."
        uses: actions/setup-java@v4
        with:
          java-version-file: map/.java-version
          distribution: temurin

      - uses: mxschmitt/action-tmate@v3
        with:
          detached: true # Continue execution, set to false to block exactly at this step.
          limit-access-to-actor: false # otherwise SSH public key error would show.

      - name: "Run map.main.kts."
        working-directory: map
        shell: bash
        run: kotlinc -script map.main.kts

      - name: "Upload 'cinemas.kml' artifact."
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: 'cinemas.kml'
          if-no-files-found: error
          path: map/cinemas.kml
