name: "🔨 Build & Execute (Map)"
on:
  workflow_call

jobs:
  run:
    # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:

      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v4

      - name: "Set up JDK 17."
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: "Run map.main.kts."
        working-directory: map
        run: kotlinc -script map.main.kts

      - name: "Upload 'cinemas.kml' artifact."
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: 'cinemas.kml'
          path: ${{ github.workspace }}/map/cinemas.kml
