name: Release to Google App Engine
on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for release'
        required: false
        default: 'Publish latest changes'
jobs:
  release:
    name: Release to Google App Engine (${{ github.event.inputs.reason }})
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      REF_TO_RELEASE: ${{ github.ref }}
    steps:
      - name: Checkout ${{ env.REF_TO_RELEASE }} branch in ${{ github.repository }} repository.
        uses: actions/checkout@v3
        with:
          ref: ${{ env.REF_TO_RELEASE }}

      - name: Validate Gradle Wrapper JARs.
        uses: gradle/wrapper-validation-action@v1

      - name: Build Frontend
        working-directory: Heroku
        env:
          NODE_ENV: production
          # Install `devDependencies`, so `npm build` runs `webpack` correctly.
          NPM_CONFIG_PRODUCTION: false
        run: |
          npm install
          cd frontend
          npm run build:prod

      - name: Build Backend
        working-directory: Heroku
        run: |
          ./gradlew :backend:endpoint:jar

      - name: Publish
        working-directory: Heroku
        run: |
          ./gradlew :deploy:appengine:appengineDeploy
