name: Sync from source
on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 3 * * *'

jobs:
  sync: # based on scripts/heroku-scheduler-sync-with-history.sh
    name: Sync from source with history
    # Doesn't matter which one, simple git commands only.
    runs-on: ubuntu-latest
    # Simple fast-forward merge, shouldn't take long.
    timeout-minutes: 15
    env:
      HISTORY_REPO: TWiStErRob/net.twisterrob.cinema.history
      HISTORY_DIR: Heroku/backend/sync/build/sync
    steps:
      - name: Checkout ${{ github.ref }} branch in ${{ github.repository }} repository.
        uses: actions/checkout@v3

      - name: Checkout default branch in ${{ env.HISTORY_REPO }} repository.
        uses: actions/checkout@v3
        with:
          repository: ${{ env.HISTORY_REPO }}
          path: ${{ env.HISTORY_DIR }}
          ssh-key: ${{ secrets.HISTORY_REPO_DEPLOY_KEY }}

      - name: Clean up workspace in ${{ env.HISTORY_DIR }}.
        working-directory: ${{ env.HISTORY_DIR }}
        run: |
          rm --verbose --force weekly_film_times.xml
          rm --verbose --force weekly_film_times_ie.xml
          rm --verbose --force weekly_film_times.log
      
      - name: Build and Run Sync.
        env:
          NEO4J_URL: ${{ secrets.NEO4J_URL }}
        working-directory: Heroku
        # HISTORY_DIR is absolute, `tee` needs a relative path.
        run: >
          ./gradlew
          :backend:sync:run
          --args "cinemas films performances"
          2>&1 | tee backend/sync/build/sync/weekly_film_times.log

      - name: Save changes to history.
        working-directory: ${{ env.HISTORY_DIR }}
        if: success() || failure()
        run: |
          git add .
          git status
          git config user.email "github-scheduler+sync@twisterrob.net"
          git config user.name "GitHub Scheduler"
          git commit -m "GitHub Scheduler: Sync"
          git push
