name: "Release from main"

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for release'
        required: false
        default: 'Publish latest changes from main'

jobs:

  release:
    name: "Release to release branch (${{ github.event.inputs.reason }})"
    runs-on: ubuntu-22.04
    # Simple fast-forward merge, shouldn't take long.
    timeout-minutes: 1
    env:
      RELEASE_BRANCH: 'release'
      TRIGGER_BRANCH: 'main'
    steps:
      - name: "Checkout ${{ env.RELEASE_BRANCH }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v4
        with:
          ref: ${{ env.RELEASE_BRANCH }}

      - name: "Merge ${{ env.TRIGGER_BRANCH }} into ${{ env.RELEASE_BRANCH }}."
        run: |
          git fetch origin ${{ env.TRIGGER_BRANCH }}
          git merge --ff-only origin/${{ env.TRIGGER_BRANCH }}

      - name: "Publish ${{ env.RELEASE_BRANCH }} to GitHub."
        run: git push origin ${{ env.RELEASE_BRANCH }}:${{ env.RELEASE_BRANCH }}

      - name: "Trigger Deployment."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # https://stackoverflow.com/a/71955944/253468
        run: >
          gh
          workflow run
          'Deploy to Google App Engine.yml'
          -f production=true
          -f reason='${{ github.event.inputs.reason }}'
