name: Release to Heroku from master
on:
  workflow_dispatch
jobs:
  release:
    name: Release to heroku branch
    # Doesn't matter which one, simple git commands only.
    runs-on: ubuntu-latest
    # Simple fast-forward merge, shouldn't take long.
    timeout-minutes: 1
    env:
      HEROKU_BRANCH: 'heroku1'
      RELEASE_BRANCH: 'master'
    steps:
      - name: Checkout ${{ env.HEROKU_BRANCH }} branch in ${{ github.repository }} repository.
        uses: actions/checkout@v2
        with:
          ref: ${{ env.HEROKU_BRANCH }}

      - name: Merge ${{ env.RELEASE_BRANCH }} into ${{ env.HEROKU_BRANCH }}.
        run: |
          git fetch origin ${{ env.RELEASE_BRANCH }}
          git merge --ff-only origin/${{ env.RELEASE_BRANCH }}

      - name: Publish ${{ env.HEROKU_BRANCH }} to GitHub.
        run: git push origin ${{ env.HEROKU_BRANCH }}:${{ env.HEROKU_BRANCH }}
