name: Generate random data
on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 3 * * *'

jobs:
  generate:
    name: Sync from source with history
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:

      - name: Set up JDK 17.
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Checkout ${{ github.ref }} branch in ${{ github.repository }} repository.
        uses: actions/checkout@v3

      - name: Clean up workspace.
        run: |
          rm --verbose --force backend/sync/test/weekly_film_times.xml
          #rm --verbose --force backend/sync/test/weekly_film_times_ie.xml

      - name: Generate random data.
        env:
          NEO4J_URL: ${{ secrets.NEO4J_URL }}
        working-directory: Heroku
        run: >
          ./gradlew
          :backend:sync:generate
          --args="test/weekly_film_times.xml"

      - name: Import generated data
        env:
          NEO4J_URL: ${{ secrets.NEO4J_URL }}
        working-directory: Heroku
        run: >
          ./gradlew
          :backend:sync:run
          --args="--folder=test performances"
